export default {
    // Regular: 'adihaus-regular',
    // Bold: 'adihaus-bold',
    // Italic: 'adihaus-italic',
    // Black: 'Barlow-Black',
    // BoldItalic: 'Barlow-BoldItalic',
    // ExtraBold: 'Barlow-ExtraBold',
    // ExtraBoldItalic: 'Barlow-ExtraBoldItalic',
    // ExtraLight: 'Barlow-ExtraLight',
    // ExtraLightItalic: 'Barlow-ExtraLightItalic',
    // Light: 'Barlow-Light',
    // LightItalic: 'Barlow-LightItalic',
    // Medium: 'Barlow-Medium',
    // MediumItalic: 'Barlow-MediumItalic',
    // SemiBold: 'Barlow-SemiBold',
    // SemiBoldItalic: 'Barlow-SemiBoldItalic',
    // Thin: 'Barlow-Thin',
    // ThinItalic: 'Barlow-ThinItalic',
  };
  