export default {
    girlOne: require('../assets/images/girl.png'),
    girlTwo: require('../assets/images/girl_1.png'),
    girlThree: require('../assets/images/girl_2.png'),
    cityImg: require('../assets/images/city_img.png'),
    maleImg: require('../assets/images/male.png'),
    femaleImg: require('../assets/images/female.png'),
    locationImg: require('../assets/images/location.png'),
    arrowBackImg: require('../assets/images/arrow_back.png'), 
    messageImg: require('../assets/images/message.png'), 
    menuImg: require('../assets/images/menu.png'),
    restaurantImg_1: require('../assets/images/restaurant_1.jpeg'),
    restaurantImg_2: require('../assets/images/restaurant_2.jpg'),
    restaurantImg_3: require('../assets/images/resturant_3.jpg'),
    restaurantImg_4: require('../assets/images/restaurant_4.jpg'),
    noDataImg: require('../assets/images/no_data.png'),
    searchImg: require('../assets/images/search.png'),
    cancelImg: require('../assets/images/cancel.png'),
    starImg: require('../assets/images/star.png'),
    heartImg: require('../assets/images/heart.png'),
    closeImg: require('../assets/images/close.png'),
    dashboardImg: require('../assets/images/dashboard.png'),
    browseImg: require('../assets/images/browse.png'),
    matchImg: require('../assets/images/matches.png'),
    qrCodeImg: require('../assets/images/qr_code.png'),
    settingsImg: require('../assets/images/settings.png'),
    chatBgImg: require('../assets/images/chat_bg.jpg'),
    manOneImg: require('../assets/images/man_one.jpg'),
    manTwoImg: require('../assets/images/man_two.jpg'),
    manThreeImg: require('../assets/images/man_three.jpg'),
    logoutImg: require('../assets/images/logout.png'),
  };
  