export default {
    createAccount: 'Create an account',
    alreadyHaveAnAcc:'Already have an account? ',
    signIn:'Sign In',
    getStarted:'Get Started',
    checkedIn:'Checked In',
    chatTxt:'Flirt, chat and meet people around you',
    signUpTxt:'SIGN UP NOW',
    loginTxt:'Login',
    emailTxt:'EMAIL ADDRESS/PHONE NUMBER',
    enterEmailTxt:'Enter Email or Phone Number',
    password:'Password',
    enterPass:'Enter Password',
    forgotPass:'Forgot Password',
    dontHaveAcc:'Don’t have an account?',
    signUp:'Sign Up',
    mobileNumber:'Mobile Number',
    enterMobileNum:'Enter your mobile number',
    alreadyAMamber:'Already a member?',
    basicInfo:'Basic Information',
    firstName:'First Name',
    enterFirstName:'Enter First Name',
    submit:'Submit',
    selectDate:'Select Date',
    birthday:'My Birthday',
    gender:'Gender',
    email:'Email',
    enterEmail:'Enter Email',
    takeASelfie:'Take a selfie',
    selfieSummary:'Show us how you look and get more chances to meet people!',
    takePhoto:'Take Photo',
    accessGallery:'Access Gallery',
    accessLiveLoc:'Access Live Locations',
    locationSummary:'Search hangout places near by to Locate your matches',
    startExploring:'Start Exploring',
    verifyMobile:'Verify Your Mobile Number',
    oneTimeOtp:'One Time Password sent on your mobile number',
    resendOtp:'Resend OTP',
  };
  